name: Ping website 1
on:
  workflow_dispatch:
  schedule:
    - cron: '0/6 * * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
jobs:
  run:
    name: Ping website
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - name: Ping
        run: |
          curl "$WEBSITE_URL"
